version: '3.8'

services:
  data-sinks:
    image: alpine:latest
    container_name: data-sinks-container
    labels:
      - "promtail.scrape=true"
    restart: always

    volumes:
      - data_sinks_code:/app

    environment:
      - USER_NAME=${USER_NAME}
      - PASSWORD=${PASSWORD}
      - GROUP_ID=${GROUP_ID}
      - KAFKA_TOPIC=${KAFKA_TOPIC}
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - COUCHDB_IP=${COUCHDB_IP}
      - DB_NAME=${DB_NAME}
      - RELEASE_VERSION=${RELEASE_VERSION}
      
    networks:
      - default

    entrypoint: |
      /bin/sh -c "
      # 1. Install Python 3 & basic tools
      apk add --no-cache python3 py3-pip tar curl;

      # 2. Download code if it does not exist locally
      if [ ! -d /app/data-sinks-v${RELEASE_VERSION} ]; then
        mkdir -p /app/data-sinks-v${RELEASE_VERSION} && \
        curl -L https://github.com/DevinMB/data-sinks/archive/refs/tags/v${RELEASE_VERSION}.tar.gz \
        | tar xz --strip-components=1 -C /app/data-sinks-v${RELEASE_VERSION};
      fi

      # 3. Install Python dependencies
      if [ -f /app/data-sinks-v${RELEASE_VERSION}/requirements.txt ]; then
        pip3 install -r /app/data-sinks-v${RELEASE_VERSION}/requirements.txt --break-system-packages;
      else
        echo 'No requirements.txt found, skipping installation';
      fi

      # 4. Run Python script
      python3 /app/data-sinks-v${RELEASE_VERSION}/couchdb-sink.py;

      # 5. Keep container running
      tail -f /dev/null
      "
networks:
  default:
    driver: bridge

volumes:
  data_sinks_code:
